# Generated by Django 3.0.6 on 2020-05-08 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200506_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publicated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
