# Generated by Django 3.0.6 on 2020-05-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200515_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='category',
            new_name='profile_category',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='project_category',
        ),
    ]
