# Generated by Django 3.0.6 on 2020-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_profile_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_team',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='team', to='pages.Profile'),
        ),
    ]
