# Generated by Django 3.0.6 on 2020-05-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200528_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['start_work'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='profilecategory',
            options={'ordering': ['title'], 'verbose_name': 'Profile Category', 'verbose_name_plural': 'Profile Categories'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-completed'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['title'], 'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['index'], 'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
