# Generated by Django 3.0.6 on 2020-06-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20200603_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default='/images/projects/project-details.jpg', upload_to='images/projects/', verbose_name='project image'),
        ),
    ]
