# Generated by Django 3.0.6 on 2020-05-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time_for_colling',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
