# Generated by Django 3.0.7 on 2020-06-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_functionalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionalsettings',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
    ]
