# Generated by Django 3.0.7 on 2020-06-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20200616_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetexts',
            name='admin_exclude',
            field=models.CharField(blank=True, default='name,admin_exclude', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='functionalsettings',
            name='admin_exclude',
            field=models.CharField(blank=True, default='name,admin_exclude', max_length=600, null=True),
        ),
    ]
