# Generated by Django 3.0.7 on 2020-06-16 04:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_auto_20200616_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetextstranslation',
            name='banner_big_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='banner big text'),
        ),
    ]
