# Generated by Django 3.0.7 on 2020-06-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_pagetexts_add_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='design', editable=False, max_length=200, null=True, verbose_name='name')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='info')),
                ('button_color', models.CharField(blank=True, choices=[('default', 'default'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('link', 'link'), ('disable', 'disable')], default='success', max_length=100, null=True, verbose_name='button_color')),
                ('button_size', models.CharField(blank=True, choices=[(' e-large', 'extralarge'), (' large', 'large'), (' ', 'default'), (' medium', 'medium'), (' small', 'small')], default=' ', max_length=100, null=True, verbose_name='button_size')),
                ('button_form', models.CharField(blank=True, choices=[(' ', 'square default'), ('-border', 'square border'), (' radius', 'radius'), ('-border radius', 'radius border'), (' circle', 'circle'), ('-border circle', 'circle border'), (' circle arrow', 'circle arrow'), ('-border circle arrow', 'circle arrow border')], default=' radius', max_length=100, null=True, verbose_name='button_form')),
                ('home_banner_text_align', models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='center', max_length=100, null=True, verbose_name='home_banner_text_align')),
                ('main_text_color', models.CharField(blank=True, default='black', max_length=200, null=True, verbose_name='main_text_color (#000000 or black)')),
                ('main_menu_text_color', models.CharField(blank=True, default='black', max_length=200, null=True, verbose_name='main_menu_color (#000000 or white)')),
                ('background_color', models.CharField(blank=True, default='lightgray', max_length=200, null=True, verbose_name='main_text_color (#000000 or black)')),
                ('container_color', models.CharField(blank=True, default='white', max_length=200, null=True, verbose_name='main_text_color (#000000 or black)')),
                ('vertical_lines_color', models.CharField(blank=True, default='gray', max_length=200, null=True, verbose_name='main_text_color (#000000 or black)')),
                ('background_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/background/', verbose_name='background_image')),
                ('full_top_banner', models.BooleanField(default=True, verbose_name='full_top_banner')),
                ('menu_left', models.BooleanField(default=False, verbose_name='menu_left')),
                ('vertical_lines', models.BooleanField(default=False, verbose_name='vertical_lines')),
            ],
            options={
                'verbose_name': 'Design Settings',
                'verbose_name_plural': 'Design Settings',
            },
        ),
        migrations.AlterField(
            model_name='functionalsettings',
            name='project_category',
            field=models.BooleanField(default=False, verbose_name='project_category'),
        ),
    ]
