# Generated by Django 3.0.7 on 2020-06-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_auto_20200617_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetextstranslation',
            name='browser_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='browser_title'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], default='default', max_length=200, null=True, verbose_name='fonts'),
        ),
    ]
