# Generated by Django 3.0.7 on 2020-06-17 21:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0014_auto_20200617_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetextstranslation',
            name='add_other_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='add_other_text'),
        ),
    ]
