# Generated by Django 3.0.7 on 2020-06-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0019_designsettings_main_menu_text_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='logo_height',
            field=models.CharField(blank=True, default=30, max_length=50, null=True, verbose_name='logo_height (30)'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='logo_width',
            field=models.CharField(blank=True, default=120, max_length=50, null=True, verbose_name='logo_width (120)'),
        ),
    ]
