# Generated by Django 3.0.7 on 2020-06-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0021_designsettings_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsettings',
            name='home_banner_text_align',
        ),
        migrations.AddField(
            model_name='designsettings',
            name='home_banner_text_align_horizontal',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='center', max_length=100, null=True, verbose_name='home_banner_text_align_horizontal'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='home_banner_text_align_vertical',
            field=models.CharField(blank=True, choices=[('start', 'start'), ('center', 'center'), ('end', 'end')], default='center', max_length=100, null=True, verbose_name='home_banner_text_align_vertical'),
        ),
    ]
