# Generated by Django 3.0.7 on 2020-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0022_auto_20200619_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsettings',
            name='home_banner_text_align_vertical',
            field=models.CharField(blank=True, choices=[('align-items-start', 'start'), ('align-items-center', 'center'), ('align-items-end', 'end')], default='center', max_length=100, null=True, verbose_name='home_banner_text_align_vertical'),
        ),
    ]
