# Generated by Django 3.0.7 on 2020-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0025_auto_20200620_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsettings',
            name='overlay_opacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='overlay_opacity (from 0.1 to 0.9)'),
        ),
    ]
