# Generated by Django 3.0.7 on 2020-06-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0028_auto_20200621_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsettings',
            name='home_banner_text_align_horizontal',
            field=models.CharField(blank=True, choices=[('ttl', 'left'), ('justify-content-center', 'center'), ('ttr', 'right')], default='center', max_length=100, null=True, verbose_name='home_banner_text_align_horizontal'),
        ),
    ]
