# Generated by Django 3.0.7 on 2020-06-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0036_designsettings_preview_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsettings',
            name='preview_background_color',
        ),
    ]
