# Generated by Django 3.0.7 on 2020-06-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0041_auto_20200626_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettingstranslation',
            name='contact_button_text',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='contact_button_text'),
        ),
    ]
