# Generated by Django 3.0.7 on 2020-06-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0043_auto_20200626_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettingstranslation',
            name='callto_banner_button_text',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='callto_banner_button_text'),
        ),
    ]
