# Generated by Django 3.0.7 on 2020-06-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0047_auto_20200628_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsettings',
            name='main_menu_text_color',
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='main_menu_text_size',
        ),
        migrations.AddField(
            model_name='designsettings',
            name='banner_title_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='banner_title_color (#000000 or white)'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='banner_title_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], default='default', max_length=200, null=True, verbose_name='banner_title_font'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='banner_title_size',
            field=models.CharField(blank=True, default=14, max_length=50, null=True, verbose_name='banner_title_size px'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='big_title_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='big_title_color (#000000 or black)'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='big_title_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], default='default', max_length=200, null=True, verbose_name='big_title_font'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='big_title_size',
            field=models.CharField(blank=True, default=14, max_length=50, null=True, verbose_name='big_title_size px'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='date_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='date_color (#000000 or white)'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='date_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], default='default', max_length=200, null=True, verbose_name='date_font'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='date_size',
            field=models.CharField(blank=True, default=14, max_length=50, null=True, verbose_name='date_size px'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='footer_text_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='footer_text_color (#000000 or white)'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='footer_text_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], default='default', max_length=200, null=True, verbose_name='footer_text_font'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='footer_text_size',
            field=models.CharField(blank=True, default=14, max_length=50, null=True, verbose_name='footer_text_size px'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='main_text_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], default='default', max_length=200, null=True, verbose_name='main_text_font'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='main_text_size',
            field=models.CharField(blank=True, default=14, max_length=50, null=True, verbose_name='main_text_size px'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='menu_text_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='menu_text_color (#000000 or white)'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='menu_text_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], default='default', max_length=200, null=True, verbose_name='menu_text_font'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='menu_text_size',
            field=models.CharField(blank=True, default=14, max_length=50, null=True, verbose_name='menu_text_size px'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='small_title_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='small_title_color (#000000 or white)'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='small_title_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], default='default', max_length=200, null=True, verbose_name='small_title_font'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='small_title_size',
            field=models.CharField(blank=True, default=14, max_length=50, null=True, verbose_name='small_title_size px'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='banner_height',
            field=models.CharField(blank=True, default=300, max_length=50, null=True, verbose_name='banner_height px'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], default='default', max_length=200, null=True, verbose_name='fonts_for_all_site'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='home_banner_height',
            field=models.CharField(blank=True, default=950, max_length=50, null=True, verbose_name='home_banner_height px'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='vertical_lines_width',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='vertical_lines_width px'),
        ),
    ]
