# Generated by Django 3.0.7 on 2020-06-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0048_auto_20200629_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsettings',
            name='banner_title_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], max_length=200, null=True, verbose_name='banner_title_font'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='big_title_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], max_length=200, null=True, verbose_name='big_title_font'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], default='Poppins, sans-serif', max_length=200, null=True, verbose_name='fonts_for_all_site'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='main_text_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], max_length=200, null=True, verbose_name='main_text_font'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='menu_text_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], max_length=200, null=True, verbose_name='menu_text_font'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='small_title_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], max_length=200, null=True, verbose_name='small_title_font'),
        ),
    ]
