# Generated by Django 3.0.7 on 2020-07-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0049_auto_20200629_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsettings',
            name='banner_title_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='banner_title_size px'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='big_title_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='big_title_size px'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='date_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='date_size px'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='footer_text_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='footer_text_size px'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='main_text_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='main_text_size px'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='menu_text_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='menu_text_size px'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='small_title_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='small_title_size px'),
        ),
    ]
