# Generated by Django 3.0.7 on 2020-07-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0051_auto_20200702_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsettings',
            name='button_text_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='button_text_color (#000000 or white)'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='button_text_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], max_length=200, null=True, verbose_name='button_text_font'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='button_text_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='button_text_size px'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='date_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], max_length=200, null=True, verbose_name='date_font'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='footer_text_font',
            field=models.CharField(blank=True, choices=[('Poppins, sans-serif', 'default'), ('Sriracha, cursive', 'Sriracha'), ('Lato, sans-serif', 'Lato'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Caveat, cursive', 'Caveat'), ('Yanone Kaffeesatz, sans-serif', 'Yanone Kaffeesatz'), ('Inconsolata, monospace', 'Inconsolata'), ('Rubik, sans-serif', 'Rubik'), ('Merriweather, serif', 'Merriweather'), ('Arizonia, cursive', 'Arizonia'), ('Permanent Marker, cursive', 'Permanent Marker'), ('Marck Script, cursive', 'Marck Script')], max_length=200, null=True, verbose_name='footer_text_font'),
        ),
    ]
