# Generated by Django 3.0.7 on 2020-06-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_functionalsettings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionalsettings',
            name='admin_exclude',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='functionalsettings',
            name='contact_form',
            field=models.BooleanField(default=True, verbose_name='contact_form'),
        ),
        migrations.AddField(
            model_name='pagepictures',
            name='preview_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagepictures',
            name='preview_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
