# Generated by Django 3.0.7 on 2020-06-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_auto_20200616_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='background_image_on',
            field=models.BooleanField(default=False, verbose_name='background_image_on'),
        ),
    ]
