# Generated by Django 3.0.7 on 2020-06-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_auto_20200617_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsettings',
            name='fonts',
            field=models.CharField(blank=True, choices=[("'Poppins', sans-serif", 'default'), ("'Sriracha', cursive", 'Sriracha'), ("'Lato', sans-serif", 'Lato'), ("'Roboto', sans-serif", 'Roboto'), ("'Open Sans', sans-serif", 'Open Sans'), ("'Caveat', cursive", 'Caveat'), ("'Yanone Kaffeesatz', sans-serif", 'Yanone Kaffeesatz'), ("'Inconsolata', monospace", 'Inconsolata'), ("'Rubik', sans-serif", 'Rubik'), ("'Merriweather', serif", 'Merriweather'), ("'Arizonia', cursive", 'Arizonia'), ("'Permanent Marker', cursive", 'Permanent Marker'), ("'Marck Script', cursive", 'Marck Script')], default='default', max_length=200, null=True, verbose_name='fonts'),
        ),
    ]
