# Generated by Django 3.0.7 on 2020-06-17 12:15

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_auto_20200617_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('home_big_banner_button', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='home_big_banner_button')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='design.DesignSettings')),
            ],
            options={
                'verbose_name': 'Design Settings Translation',
                'db_table': 'design_designsettings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
