# Generated by Django 3.0.7 on 2020-06-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_designsettingstranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designsettings',
            old_name='fonts',
            new_name='font',
        ),
    ]
