# Generated by Django 3.0.7 on 2020-06-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_pagetextstranslation_add_other_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsettings',
            name='background_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='background_color (#000000 or black)'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='container_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='container_color (#000000 or black)'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='main_menu_text_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='main_menu_text_color (#000000 or white)'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='main_text_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='main_text_color (#000000 or black)'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='vertical_lines_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vertical_lines_color (#000000 or black)'),
        ),
    ]
