# Generated by Django 3.0.7 on 2020-06-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0016_auto_20200619_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='social_icons_size',
            field=models.CharField(blank=True, default=20, max_length=50, null=True, verbose_name='social_icons_size'),
        ),
    ]
