# Generated by Django 3.0.7 on 2020-06-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_designsettings_social_icons_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designsettings',
            name='social_icons_size',
        ),
        migrations.AddField(
            model_name='designsettings',
            name='social_icons_footer_size',
            field=models.CharField(blank=True, default=30, max_length=50, null=True, verbose_name='social_icons_footer_size'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='social_icons_top_size',
            field=models.CharField(blank=True, default=20, max_length=50, null=True, verbose_name='social_icons_top_size'),
        ),
    ]
