# Generated by Django 3.0.7 on 2020-06-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0018_auto_20200619_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='main_menu_text_size',
            field=models.CharField(blank=True, default=14, max_length=50, null=True, verbose_name='main_menu_text_size'),
        ),
    ]
