# Generated by Django 3.0.7 on 2020-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0020_auto_20200619_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
