# Generated by Django 3.0.7 on 2020-06-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0030_auto_20200621_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='vertical_lines_width',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='vertical_lines_width 3 or 5'),
        ),
    ]
