# Generated by Django 3.0.7 on 2020-06-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0031_designsettings_vertical_lines_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='overlay_default',
            field=models.BooleanField(default=True, verbose_name='top_navigation'),
        ),
    ]
