# Generated by Django 3.0.7 on 2020-06-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0032_designsettings_overlay_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsettings',
            name='overlay_default',
            field=models.BooleanField(default=True, verbose_name='overlay_default'),
        ),
    ]
