# Generated by Django 3.0.7 on 2020-06-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0033_auto_20200624_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsettings',
            name='home_banner_text_align_horizontal',
            field=models.CharField(blank=True, choices=[('ttl', 'left'), ('justify-content-center', 'center'), ('ttr', 'right')], default='justify-content-center', max_length=100, null=True, verbose_name='home_banner_text_align_horizontal'),
        ),
        migrations.AlterField(
            model_name='designsettings',
            name='home_banner_text_align_vertical',
            field=models.CharField(blank=True, choices=[('align-items-start', 'start'), ('align-items-center', 'center'), ('align-items-end', 'end')], default='align-items-center', max_length=100, null=True, verbose_name='home_banner_text_align_vertical'),
        ),
    ]
