# Generated by Django 3.0.7 on 2020-06-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0034_auto_20200624_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='footer_background_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='footer_background_color (#000000 or black)'),
        ),
    ]
