# Generated by Django 3.0.7 on 2020-06-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0037_remove_designsettings_preview_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='footer_font_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='footer_background_color (#000000 or black)'),
        ),
    ]
