# Generated by Django 3.0.7 on 2020-06-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0044_designsettingstranslation_callto_banner_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetexts',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='pagetexts',
            name='add_name',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='add_name_to_bannertext'),
        ),
    ]
