# Generated by Django 3.0.7 on 2020-06-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0045_auto_20200627_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetexts',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='pagetexts',
            name='add_name',
            field=models.BooleanField(default=False, verbose_name='add_name_to_bannertext'),
        ),
    ]
