# Generated by Django 3.0.7 on 2020-06-28 17:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0046_auto_20200627_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetextstranslation',
            name='add_other_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='other text', null=True, verbose_name='add_other_text'),
        ),
        migrations.AlterField(
            model_name='pagetextstranslation',
            name='banner_big_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Banner Big Text', null=True, verbose_name='banner big text'),
        ),
        migrations.AlterField(
            model_name='pagetextstranslation',
            name='big_page_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Big page title', null=True, verbose_name='big page title'),
        ),
        migrations.AlterField(
            model_name='pagetextstranslation',
            name='browser_title',
            field=models.CharField(blank=True, default='...', max_length=100, null=True, verbose_name='browser_title'),
        ),
        migrations.AlterField(
            model_name='pagetextstranslation',
            name='small_page_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Small page title', null=True, verbose_name='small page title'),
        ),
    ]
