# Generated by Django 3.0.6 on 2020-05-29 10:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200522_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_related_name': 'user', 'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_inline',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='address_inline'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='languages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registation_number',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='registation_number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='company_name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(default='images/defaults/logo.png', upload_to='images/users/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='postal_code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_for_colling',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='time_for_colling'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='twitter'),
        ),
    ]
