# Generated by Django 3.0.6 on 2020-06-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200529_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='info'),
        ),
    ]
