# Generated by Django 3.0.7 on 2020-06-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(default='images/defaults/logo.png', upload_to='images/users/', verbose_name='logo_120x30'),
        ),
    ]
