# Generated by Django 3.0.5 on 2020-05-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='first_image',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/products/project_detail.jpg', upload_to='images/project/', verbose_name='product_image')),
                ('index', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pages.Project')),
            ],
            options={
                'verbose_name_plural': 'ProjectImages',
                'ordering': ['index'],
            },
        ),
    ]
