# Generated by Django 3.0.5 on 2020-05-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200503_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/defaults/project-details.jpg', upload_to='images/profile/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default='images/products/project_detail.jpg', upload_to='images/projects/', verbose_name='product_image'),
        ),
    ]
