# Generated by Django 3.0.6 on 2020-05-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_news_publicated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category_slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ProfileCategory',
        ),
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(default=None, related_name='profile_category', to='pages.ProfileCategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(default=None, related_name='project_category', to='pages.ProjectCategory'),
        ),
    ]
