# Generated by Django 3.0.6 on 2020-05-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200517_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='start_work',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.DateField(auto_now=True),
        ),
    ]
