# Generated by Django 3.0.6 on 2020-05-28 20:20

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20200526_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ind',
        ),
        migrations.AddField(
            model_name='project',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='images/defaults/news.jpg', upload_to='images/news/', verbose_name='news image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateField(default=datetime.date.today, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/defaults/project-details.jpg', upload_to='images/profile/', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='short_description',
            field=models.TextField(verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_work',
            field=models.DateField(auto_now=True, verbose_name='start_work'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='profilecategory',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='category_slug'),
        ),
        migrations.AlterField(
            model_name='profilecategory',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.DateField(auto_now=True, verbose_name='completed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='first_image',
            field=models.ImageField(default='images/defaults/project-details.jpg', upload_to='images/projects/', verbose_name='first_image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default='images/products/project_detail.jpg', upload_to='images/projects/', verbose_name='project image'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='title'),
        ),
    ]
