# Generated by Django 3.0.6 on 2020-06-03 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20200603_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='start_work',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start_work'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='completed'),
        ),
    ]
