# Generated by Django 3.0.7 on 2020-06-11 13:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20200605_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstranslation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='newstranslation',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='profiletranslation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='profiletranslation',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='short_description'),
        ),
    ]
