# Generated by Django 3.0.7 on 2020-06-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20200611_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='images/defaults/news.jpg', upload_to='images/services/', verbose_name='news image'),
        ),
    ]
