# Generated by Django 3.0.7 on 2020-06-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='images/defaults/news.jpg', null=True, upload_to='images/services/', verbose_name='news image'),
        ),
    ]
