# Generated by Django 3.0.7 on 2020-06-11 13:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetextstranslation',
            name='big_page_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='big page title'),
        ),
        migrations.AlterField(
            model_name='pagetextstranslation',
            name='small_page_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='small page title'),
        ),
    ]
